stages:
  - build
  - package
  - deploy

variables:
  DOCKER_REGISTRY: localhost:5000
  IMAGE_NAME: vue-login

# 빌드 단계
build:
  stage: build
  image: node:16
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

# Docker 이미지 생성 및 푸시
package:
  stage: package
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - docker build -t $DOCKER_REGISTRY/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - docker push $DOCKER_REGISTRY/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker tag $DOCKER_REGISTRY/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA $DOCKER_REGISTRY/$IMAGE_NAME:latest
    - docker push $DOCKER_REGISTRY/$IMAGE_NAME:latest

# Kubernetes 배포
deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - sed -i "s|\${DOCKER_REGISTRY}|$DOCKER_REGISTRY|g" kubernetes/frontend-deployment.yaml
    - sed -i "s|:latest|:$CI_COMMIT_SHORT_SHA|g" kubernetes/frontend-deployment.yaml
    - kubectl apply -f kubernetes/frontend-deployment.yaml
    - kubectl apply -f kubernetes/frontend-service.yaml
  only:
    - main